apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseball.fullname" . }}-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5ob21lLmdscm9sYW5kLmNvbSI6IHsKICAgICAgImF1dGgiOiAiWW1GelpXSmhiR3dyYjJOd09rWk1URGN6U1ZkRU5GTlZTems1UlRkT05GQlVOVEpWTWtvNFdqSXpRVE5WTTBrek1qVlBSa1k1TTBwSlQwVkdSRTVMV1VGTlNWSk1SbGRQUmxOUk9FOD0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
